# Generated by Django 4.2.6 on 2023-10-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asosiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('janr', models.CharField(blank=True, choices=[('Badiy', 'Badiy'), ('Ilmiy', 'Ilmiy')], max_length=8)),
                ('sahifa', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('ish_vaqti', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('jins', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('tugilgan_sana', models.DateField()),
                ('kitoblar_soni', models.PositiveSmallIntegerField()),
                ('tirik', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kurs', models.PositiveSmallIntegerField()),
                ('kitob_soni', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateField()),
                ('qaytardi', models.BooleanField(blank=True, default=False)),
                ('asosiy', models.ManyToManyField(to='asosiy.asosiy')),
                ('kutubxonachi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kutubxonachi')),
                ('talaba', models.ManyToManyField(to='asosiy.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='asosiy',
            name='muallifi',
            field=models.ManyToManyField(to='asosiy.muallif'),
        ),
    ]
