# Generated by Django 4.2.6 on 2023-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='asosiy',
            new_name='kitoblar',
        ),
        migrations.AlterField(
            model_name='asosiy',
            name='sahifa',
            field=models.PositiveBigIntegerField(),
        ),
    ]
