# Generated by Django 4.2.6 on 2023-10-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_kitob_record_kitoblar_alter_kitob_sahifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asosiy',
            name='muallifi',
        ),
        migrations.RemoveField(
            model_name='record',
            name='kitoblar',
        ),
        migrations.AddField(
            model_name='asosiy',
            name='muallif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.muallif'),
        ),
        migrations.AddField(
            model_name='record',
            name='asosiy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.asosiy'),
        ),
        migrations.AddField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='kutubxonachi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.kutubxonachi'),
        ),
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytardi',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='record',
            name='talaba',
        ),
        migrations.AddField(
            model_name='record',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.talaba'),
        ),
    ]
