# Generated by Django 4.2.6 on 2023-10-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_remove_kitob_muallifi_remove_record_kitoblar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asosiy',
            new_name='Kitob',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='asosiy',
            new_name='kitob',
        ),
    ]
